services:
  # docker-compose up --build
  # --- BANCO DE DADOS (Agora dentro do grupo) ---
  db:
    image: mysql:latest
    container_name: nossozelo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nossozelo123
      MYSQL_DATABASE: db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql # Isso mantém seus dados salvos
    networks:
      - nossozelo_network

  # --- BACKEND ---
  backend:
    build: ./server
    container_name: nossozelo_backend
    restart: always
    ports:
      - '4000:4000'
    environment:
      # 🔥 MUDANÇA IMPORTANTE: Agora usamos o nome do serviço 'db' em vez de host.docker.internal
      - DATABASE_URL=mysql://root:nossozelo123@db:3306/db
      - PORT=4000
      - API_URL=http://192.168.0.3:4000
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - nossozelo_network

  # --- FRONTEND ---
  frontend:
    build: ./client
    container_name: nossozelo_frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.0.3:4000
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - nossozelo_network

networks:
  nossozelo_network:
    driver: bridge

volumes:
  mysql_data: # Define onde o volume do banco será guardado
