ALTER TABLE `planos`
  ADD COLUMN `descricao` TEXT NULL,
  ADD COLUMN `ativo` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `ordem` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `criado_em` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  ADD COLUMN `atualizado_em` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
